### ISSUE TITLE
Add ability to see the other person's letter even after starting a chat

### ISSUE THREAD

**Issue by sebastianquek** [LetterboxDev/frontend#119]
So that you can see what questions were answered, and how they were answered.

**Comment by lozy219** [comment]
it might not work until @ianngiaw merge my backend pr and deploy it

**Comment by sebastianquek** [comment]
Add a dropdown to see either responses or profile.
Profile will be the standard home profile card.
Reponses will be the standard one, but without flipping.

**Comment by ianngiaw** [comment]
Added dropdown. Added methods to get data for the profile and responses. Now just need to do the pages themselves. Can someone do?
