### ISSUE TITLE
Clicking home in the popup that appears after updating profile opens home as a sub-page

### ISSUE THREAD

**Issue by ianngiaw** [LetterboxDev/frontend#132]

**Comment by lozy219** [comment]
cannot reproduce?

**Comment by ianngiaw** [comment]
@lozy219 It happens to me when i do it twice. Open the app, go to profile, change the answer for one question, tap update, tap home, open the sidebar and go back to profile, change the answer back, tap update, tap home, home is now a sub page for me

**Comment by lozy219** [comment]
:+1:  change profile picture will not have this problem

**Comment by ianngiaw** [comment]
@lozy219 It doesn't happen when changing profile picture because changing profile picture doesn't require the update button i guess
