### ISSUE TITLE
Chat view manual enter detection

### ISSUE THREAD

**Issue by xbili** [LetterboxDev/frontend#61]
Detect when a user hits enter when the textarea in the chat view is in focus. Enter press will be treated as a submit.

**Comment by ianngiaw** [comment]
What is this issue about again?

**Comment by ianngiaw** [comment]
Oh okay nevermind, I get it. I'll add a description so i don't get confused again

**Comment by xbili** [comment]
@ianngiaw oops hahah I didn't add in a description.
