### ISSUE TITLE
digest loop on ios

### ISSUE THREAD

**Issue by lozy219** [LetterboxDev/frontend#83]
![image](https://cloud.githubusercontent.com/assets/6064797/10712372/c4f31f5a-7acb-11e5-8e1f-e882e1884a7e.png)

does it work on Android??

**Comment by xbili** [comment]
At which view is this?

**Comment by lozy219** [comment]
@xbili everywhere
see http://stackoverflow.com/questions/32632888/ionic-app-ios-9-problems-rootscopeinfdig-10-digest-iterations-reached
