### ISSUE TITLE
navbar minor styling issue

### ISSUE THREAD

**Issue by lozy219** [LetterboxDev/frontend#84]
![image](https://cloud.githubusercontent.com/assets/6064797/10712378/f7c9b948-7acb-11e5-8195-4e8148fdeff2.png)

**Comment by xbili** [comment]
What are the possible solutions for this lol

**Comment by lozy219** [comment]
@xbili change Notifications to something else shorter? what's the corresponding terms in 'letterbox' world? News?

**Comment by sebastianquek** [comment]
Can we just use "Back"?

**Comment by sebastianquek** [comment]
Not reproducible.
