### ISSUE TITLE
Keyboard should stay open after submitting messages

### ISSUE THREAD

**Issue by sebastianquek** [LetterboxDev/frontend#91]

**Comment by ianngiaw** [comment]
@sebastianquek It stays open if you click enter instead of the button.

**Comment by sebastianquek** [comment]
Yes, it should also stay open when pressing the submit button.

**Comment by xbili** [comment]
Can someone with a native app fix this? It's a bit hard for me to test this on desktop.

**Comment by lozy219** [comment]
it's actually quite tricky to deal with focus on native app.. now I set the textarea 'always focused' after being focused for the first time
